### ISSUE TITLE
web compile error

### ISSUE THREAD

**Issue by nices0325** [aws-samples/aws-appsync-iot-core-realtime-dashboard#10]
I updated npm version to the latest, then compile error occurs

/Users/jojaehyeong/aws-appsync-iot-core-realtime-dashboard/web/src/components/LineChartWidget/LineChartWidget.tsx
TypeScript error in /Users/jojaehyeong/aws-appsync-iot-core-realtime-dashboard/web/src/components/LineChartWidget/LineChartWidget.tsx(7,10):
Property 'global' does not exist on type 'Defaults'.  TS2339

     5 | import { ChartOptions, defaults } from 'chart.js';
     6 | 
  >  7 | defaults.global.defaultFontColor = '#ffffff';
       |          ^
     8 | 
     9 | const useStyles = makeStyles((theme: Theme) => ({
    10 |   paper: {

**Comment by dave-moser** [comment]
try using

npm install --legacy-peer-deps
