### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by nices0325** [aws-samples/aws-appsync-iot-core-realtime-dashboard#11]
npm install fail on web folder

0 verbose cli [
0 verbose cli   '/Users/jojaehyeong/.nvm/versions/node/v15.13.0/bin/node',
0 verbose cli   '/Users/jojaehyeong/.nvm/versions/node/v15.13.0/bin/npm',
0 verbose cli   'install'
0 verbose cli ]
1 info using npm@7.7.6
2 info using node@v15.13.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 3ms
5 timing config:load:file:/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/npmrc Completed in 1ms
6 timing config:load:builtin Completed in 2ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/Users/jojaehyeong/aws-appsync-iot-core-realtime-dashboard/web/.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:/Users/jojaehyeong/.npmrc Completed in 2ms
12 timing config:load:user Completed in 2ms
13 timing config:load:file:/Users/jojaehyeong/.nvm/versions/node/v15.13.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setEnvs Completed in 1ms
17 timing config:load Completed in 11ms
18 timing npm:load:configload Completed in 11ms
19 timing npm:load:setTitle Completed in 2ms
20 timing npm:load:setupLog Completed in 1ms
21 timing npm:load:cleanupLog Completed in 2ms
22 timing npm:load:configScope Completed in 0ms
23 timing npm:load:projectScope Completed in 1ms
24 timing npm:load Completed in 18ms
25 timing config:load:flatten Completed in 3ms
26 timing arborist:ctor Completed in 0ms
27 timing arborist:ctor Completed in 0ms
28 timing idealTree:init Completed in 12ms
29 timing idealTree:userRequests Completed in 0ms
30 silly idealTree buildDeps
31 silly fetch manifest @babel/cli@^7.10.1
32 http fetch GET 304 https://registry.npmjs.org/@babel%2fcli 155ms (from cache)
33 silly fetch manifest @babel/core@^7.10.2
34 http fetch GET 304 https://registry.npmjs.org/@babel%2fcore 48ms (from cache)
35 silly fetch manifest @babel/preset-env@^7.10.2
36 http fetch GET 304 https://registry.npmjs.org/@babel%2fpreset-env 45ms (from cache)
37 silly fetch manifest @material-ui/core@^4.8.3
38 http fetch GET 304 https://registry.npmjs.org/@material-ui%2fcore 76ms (from cache)
39 silly fetch manifest @types/react@^16.9.17
40 http fetch GET 304 https://registry.npmjs.org/@types%2freact 54ms (from cache)
41 silly fetch manifest react@^16.12.0
42 http fetch GET 304 https://registry.npmjs.org/react 46ms (from cache)
43 silly fetch manifest react-dom@^16.12.0
44 http fetch GET 304 https://registry.npmjs.org/react-dom 61ms (from cache)
45 silly fetch manifest @material-ui/icons@^4.5.1
46 http fetch GET 304 https://registry.npmjs.org/@material-ui%2ficons 69ms (from cache)
47 silly fetch manifest @testing-library/jest-dom@^4.2.4
48 http fetch GET 304 https://registry.npmjs.org/@testing-library%2fjest-dom 1334ms (from cache)
49 silly fetch manifest @testing-library/react@^9.4.0
50 http fetch GET 304 https://registry.npmjs.org/@testing-library%2freact 72ms (from cache)
51 silly fetch manifest @testing-library/user-event@^7.2.1
52 http fetch GET 304 https://registry.npmjs.org/@testing-library%2fuser-event 73ms (from cache)
53 silly fetch manifest @testing-library/dom@>=5
54 http fetch GET 304 https://registry.npmjs.org/@testing-library%2fdom 71ms (from cache)
55 silly fetch manifest @types/chart.js@^2.9.11
56 http fetch GET 304 https://registry.npmjs.org/@types%2fchart.js 47ms (from cache)
57 silly fetch manifest @types/jest@^24.0.25
58 http fetch GET 304 https://registry.npmjs.org/@types%2fjest 55ms (from cache)
59 silly fetch manifest @types/node@^12.12.24
60 http fetch GET 304 https://registry.npmjs.org/@types%2fnode 77ms (from cache)
61 silly fetch manifest @types/react-chartjs-2@^2.5.7
62 http fetch GET 304 https://registry.npmjs.org/@types%2freact-chartjs-2 63ms (from cache)
63 silly fetch manifest @types/react-dom@^16.9.4
64 http fetch GET 304 https://registry.npmjs.org/@types%2freact-dom 50ms (from cache)
65 silly fetch manifest @types/react-map-gl@^5.1.0
66 http fetch GET 304 https://registry.npmjs.org/@types%2freact-map-gl 51ms (from cache)
67 silly fetch manifest @types/react-router-dom@^5.1.3
68 http fetch GET 304 https://registry.npmjs.org/@types%2freact-router-dom 60ms (from cache)
69 silly fetch manifest aws-amplify@^2.2.6
70 http fetch GET 304 https://registry.npmjs.org/aws-amplify 84ms (from cache)
71 silly fetch manifest aws-amplify-react@^3.1.6
72 http fetch GET 304 https://registry.npmjs.org/aws-amplify-react 46ms (from cache)
73 silly fetch manifest @aws-amplify/analytics@^2.0.0
74 http fetch GET 304 https://registry.npmjs.org/@aws-amplify%2fanalytics 551ms (from cache)
75 silly fetch manifest @aws-amplify/api@^2.0.0
76 http fetch GET 304 https://registry.npmjs.org/@aws-amplify%2fapi 487ms (from cache)
77 silly fetch manifest @aws-amplify/pubsub@^1.2.4
78 http fetch GET 304 https://registry.npmjs.org/@aws-amplify%2fpubsub 394ms (from cache)
79 silly fetch manifest @aws-amplify/auth@^2.0.0
80 http fetch GET 304 https://registry.npmjs.org/@aws-amplify%2fauth 562ms (from cache)
81 silly fetch manifest @aws-amplify/core@^2.0.0
82 http fetch GET 304 https://registry.npmjs.org/@aws-amplify%2fcore 404ms (from cache)
83 silly fetch manifest @react-native-community/netinfo@^5.5.0
84 http fetch GET 304 https://registry.npmjs.org/@react-native-community%2fnetinfo 458ms (from cache)
85 silly fetch manifest react-native@>=0.59
86 http fetch GET 304 https://registry.npmjs.org/react-native 63ms (from cache)
87 silly fetch manifest react@17.0.1
88 timing idealTree Completed in 5921ms
89 timing command:install Completed in 5930ms
90 verbose stack Error: unable to resolve dependency tree
90 verbose stack     at Arborist.[failPeerConflict] (/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1157:25)
90 verbose stack     at Arborist.[loadPeerSet] (/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1134:34)
90 verbose stack     at async Arborist.[loadPeerSet] (/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1110:11)
90 verbose stack     at async Arborist.[loadPeerSet] (/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1110:11)
90 verbose stack     at async Arborist.[loadPeerSet] (/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1110:11)
90 verbose stack     at async Arborist.[buildDepStep] (/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:838:11)
90 verbose stack     at async Arborist.buildIdealTree (/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:209:7)
90 verbose stack     at async Promise.all (index 1)
90 verbose stack     at async Arborist.reify (/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:131:5)
90 verbose stack     at async Install.install (/Users/jojaehyeong/.nvm/versions/node/v15.13.0/lib/node_modules/npm/lib/install.js:137:5)
91 verbose cwd /Users/jojaehyeong/aws-appsync-iot-core-realtime-dashboard/web
92 verbose Darwin 20.3.0
93 verbose argv "/Users/jojaehyeong/.nvm/versions/node/v15.13.0/bin/node" "/Users/jojaehyeong/.nvm/versions/node/v15.13.0/bin/npm" "install"
94 verbose node v15.13.0
95 verbose npm  v7.7.6
96 error code ERESOLVE
97 error ERESOLVE unable to resolve dependency tree
98 error
99 error While resolving: [1mdashboard[22m@[1m0.1.0[22m
99 error Found: [1mreact[22m@[1m16.14.0[22m[2m[22m
99 error [2mnode_modules/react[22m
99 error   [1mreact[22m@"[1m^16.12.0[22m" from the root project
99 error
99 error Could not resolve dependency:
99 error [35mpeer[39m [1mreact[22m@"[1m17.0.1[22m" from [1mreact-native[22m@[1m0.64.0[22m[2m[22m
99 error [2mnode_modules/react-native[22m
99 error   [35mpeer[39m [1mreact-native[22m@"[1m>=0.59[22m" from [1m@react-native-community/netinfo[22m@[1m5.9.10[22m[2m[22m
99 error   [2mnode_modules/@react-native-community/netinfo[22m
99 error     [35mpeer[39m [1m@react-native-community/netinfo[22m@"[1m^5.5.0[22m" from [1m@aws-amplify/core[22m@[1m2.3.0[22m[2m[22m
99 error     [2mnode_modules/@aws-amplify/core[22m
99 error       [35mpeer[39m [1m@aws-amplify/core[22m@"[1m^2.0.0[22m" from [1maws-amplify-react[22m@[1m3.1.9[22m[2m[22m
99 error       [2mnode_modules/aws-amplify-react[22m
99 error       3 more (@aws-amplify/analytics, @aws-amplify/api, @aws-amplify/auth)
99 error
99 error Fix the upstream dependency conflict, or retry
99 error this command with --force, or --legacy-peer-deps
99 error to accept an incorrect (and potentially broken) dependency resolution.
99 error
99 error See /Users/jojaehyeong/.npm/eresolve-report.txt for a full report.
100 verbose exit 1

**Comment by nices0325** [comment]
how can i resolve this

**Comment by dave-moser** [comment]
React can sometimes throw that error based on what version of Node or NPM you have installed.  Try using:

npm install --legacy-peer-deps
