### ISSUE TITLE
Android complier issue 

### ISSUE THREAD

**Issue by anoopradhika** [aws-samples/aws-appsync-iot-core-realtime-dashboard#12]
Hi,
I would like to use your project for Android environment. 
I am getting this Sync error when I load this Project from "https://github.com/aws-samples/aws-appsync-iot-core-realtime-dashboard/tree/master/mobile/android"
Here the error 
```
A problem occurred evaluating settings 'mobile'.
> Could not read script 'C:\Users\XXXXXX\AndroidStudioProjects\aws-appsync-iot-core-realtime-dashboard\mobile\node_modules\@react-native-community\cli-platform-android\native_modules.gradle' as it does not exist.

```

**Comment by dave-moser** [comment]
Hi.  I only configured an coded out an iOS version of the mobile app.  I did not configure or code for Andriod.
