### ISSUE TITLE
can not upload sensor information on the map

### ISSUE THREAD

**Issue by nices0325** [aws-samples/aws-appsync-iot-core-realtime-dashboard#13]
![image](https://user-images.githubusercontent.com/73952628/116040262-c4b65e00-a6a6-11eb-9370-a90a2ac0827b.png)

I just change the analytics name ,query name, and topic name .. why doesn;t it work..

**Comment by dave-moser** [comment]
If you change the Topic Name, you likely need to change the IoT Rule that monitors the topic and sends the data to the Lambda function.
