### ISSUE TITLE
node create-sensors.js not working 

### ISSUE THREAD

**Issue by royzhao7** [aws-samples/aws-appsync-iot-core-realtime-dashboard#18]
show Error creating sensors
Missing credentials in config, if using AWS_CONFIG_FILE, set AWS_SDK_LOAD_CONFIG=1

**Comment by dave-moser** [comment]
Thanks for pointing this out.  I will take a look and supply a fix.

**Comment by dave-moser** [comment]
I have updated the app to the latest version of the aws-sdk (3.0). This resolved the issue on my machine.  Can you try to reinstall and confirm?

Thanks.
