### ISSUE TITLE
There was an error building the custom resources

### ISSUE THREAD

**Issue by perryluopl** [aws-samples/aws-appsync-iot-core-realtime-dashboard#20]
I follow the instructions.

$ cd aws-appsync-iot-core-realtime-dashboard/web
$ npm install
$ amplify init

I got the errors.
```
✖ There was an error initializing your environment.
🛑 There was an error building the custom resources
Packaging overrides failed with the error
Command failed with exit code 1: yarn install
ERROR: [Errno 2] No such file or directory: 'install'
```

node --version
v16.17.0

npm --version
8.15.0

amplify --version
10.6.1

**Comment by dave-moser** [comment]
I have updated the project with the latest versions of several packages. Can you try again? The changes were extensive, so I recommend you start with a fresh clone of the repo.
