### ISSUE TITLE
Web content is not shown due to some source map errors

### ISSUE THREAD

**Issue by zhuchuyi** [aws-samples/aws-appsync-iot-core-realtime-dashboard#25]
I installed and deployed the demo on my local PC following steps in README.md. 
When running "amplify init", there was an warning as below:
⠇ Building resource api/sensorsapi⚠️ WARNING: Schema is using an @auth directive with deprecated provider 'iam'. Replace 'iam' provider with 'identityPool' provider.
So I changed the provider to identityPool and everything was OK for "amplify init", "amplify push" and "npm run dev".
But when I opened it in Firefox, it was blank and some errors were shown on firefox debugger:

Source map error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: null
Source Map URL: installHook.js.map

Module "events" has been externalized for browser compatibility. Cannot access "events.EventEmitter" in client code. See https://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

Uncaught ReferenceError: global is not defined
    js index.js:24
    forEachArray2 index.js:12
    forEach2 index.js:54
    js index.js:22
    __require chunk-V4OQ3NZ2.js:11
    js IsTypedArrayOutOfBounds.js:11
    __require chunk-V4OQ3NZ2.js:11
    js TypedArrayCreateFromConstructor.js:8
    __require chunk-V4OQ3NZ2.js:11
    js TypedArraySpeciesCreate.js:11
    __require chunk-V4OQ3NZ2.js:11
    js implementation.js:16
    __require chunk-V4OQ3NZ2.js:11
    js index.js:6
    __require chunk-V4OQ3NZ2.js:11
    js index.js:4
    __require chunk-V4OQ3NZ2.js:11
    node_modules maplibre-gl-js-amplify.js:13657
    __require chunk-V4OQ3NZ2.js:11
    js constrain_feature_movement.js:7
    __require chunk-V4OQ3NZ2.js:11
    js move_features.js:7
    __require chunk-V4OQ3NZ2.js:11
    js DirectModeOverride.js:3
    __require chunk-V4OQ3NZ2.js:11
    js index.js:3
    __require chunk-V4OQ3NZ2.js:11
    <anonymous> AmplifyMapDraw.js:2

Source map error: No sources are declared in this source map.
Resource URL: http://localhost:5173/node_modules/.vite/deps/chunk-V4OQ3NZ2.js?v=d1a7ef4f
Source Map URL: chunk-V4OQ3NZ2.js.map

Source map error: No sources are declared in this source map.
Resource URL: http://localhost:5173/node_modules/.vite/deps/chunk-CR7QZ4QQ.js?v=d1a7ef4f
Source Map URL: chunk-CR7QZ4QQ.js.map

Source map error: No sources are declared in this source map.
Resource URL: http://localhost:5173/node_modules/.vite/deps/aws-amplify.js?v=d1a7ef4f
Source Map URL: aws-amplify.js.map

Source map error: No sources are declared in this source map.
Resource URL: http://localhost:5173/node_modules/.vite/deps/react.js?v=d1a7ef4f
Source Map URL: react.js.map

Source map error: No sources are declared in this source map.
Resource URL: http://localhost:5173/node_modules/.vite/deps/maplibre-gl.js?v=d1a7ef4f
Source Map URL: maplibre-gl.js.map

Source map error: JSON.parse: unexpected character at line 1 column 1 of the JSON data
Resource URL: null
Source Map URL: react_devtools_backend_compact.js.map

**Comment by dave-moser** [comment]
I have pushed a change to the VITE config that fixes this issue. Thanks for bringing it to my attention.
